sudo: false
language: python
python:
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libc6
install:
    - pip install -r requirements-dev.txt
    - pip install -e .
script: pytest
after_success:
    - coveralls
