sudo: false
dist: trusty
language: python
python:
    - 3.4
    - 3.5
    - 3.6
before_install:
    - pip install -U pip
install:
    - pip install -r requirements-dev.txt
    - pip install --upgrade numpy
    - pip install --upgrade scipy
    - pip install --upgrade tensorflow
    - pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
    - pip install -e .
script: pytest
after_success:
    - coveralls
cache:
    - pip
    - apt
